---
# Site settings
title: Codfish i/o
slogan: Internet
email: contact@codfish.io
description: >
  Chris O'Donnell &mdash; Web developer, not the actor. Web developing since 2007 @ Manhattan College. Senior Consultant @ EY.
url: "http://codfish.io"
twitter_username: __codfish
github_username:  codfish
permalink: /post/:title

kramdown:
  input: GFM
