name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - 'next-major'
      - '+([0-9])?(.{+([0-9]),x}).x'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: semantic release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        with:
          branches: |
            ['main', 'next', 'next-major', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
