name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run lint:commits -- --from="origin/${{ github.base_ref }}" --to="origin/${{github.head_ref }}"
